server:
  port: 80

# redis
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: root

  datasource:
    db1:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/db1?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true&autoReconnect=true
      username: root
      password: 123456

      max-active: 300
      min-idle: 20
      initial-size: 20
      max-wait: 10000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 20000

    db2:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/db2?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true&autoReconnect=true
      username: root
      password: 123456

      max-active: 300
      min-idle: 20
      initial-size: 20
      max-wait: 10000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 20000
